### ISSUE TITLE
Checked-in Firebase credentials

### ISSUE THREAD

**Issue by yudistrange** [jakemcc/backgammon#1]
Is it safe to have these credentials checked-in?

https://github.com/jakemcc/backgammon/blob/6214959e4a785708ddcf7e0fe9a6a7afbf09a9e3/src/cljs/bg/firebase.cljs#L9

**Comment by jakemcc** [comment]
@yudistrange Honestly, I'm not entirely sure and wasn't when I checked it in. I haven't been avoiding showing those keys, as the project they are for was one I specifically created for the IN/Clojure talk that this project supports. That project has since been deleted.

I've been treating them as safe to expose because the the various Firebase examples always have you just shove them straight in your static html. They need to get to the client somehow.

Normally, when using firebase you also end up authenticating the user of your app and you can restrict where someone is allowed to authenticate from. This project opens up the entire Firebase Realtime Database to allow unauthenticated access, which is definitely not a great thing and would make exposing the apikey (and other info) a bit dangerous.

I've removed the keys and added some steps to the readme that points people in the right direction for getting started with this repo.

Thanks for the question.
